apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: syntharacare-api
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/syntharacare/syntharacare-api
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: mongodb+srv://adil:qwerty123@cluster0.sewwi.mongodb.net/Synthara?retryWrites=true&w=majority&appName=Cluster0
        - name: JWT_SECRET
          value: your-super-secure-jwt-secret-key-here
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: GCS_PROJECT_ID
          value: "syntharacare"
        - name: GCS_BUCKET_NAME
          value: "syntharauibucket"
        - name: GEMINI_API_KEY
          value: AIzaSyBlmnCUVeDPrPj_zBOsneSjbI3_dlnTb2g
        - name: GCS_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: GCS_CREDENTIALS
              key: latest
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
